### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by NiekRossenInfoSupport** [vippsas/backstage-azure-resources-backend#8]
Steps to reproduce 
`cd ./packages/backend`
`yarn add @vippsno/plugin-azure-resources-backend`

In `./packages/backend/src/plugins` add a file named `azure-resources-backend.ts` with the content
```ts
import { createRouter } from '@vippsno/plugin-azure-resources-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  return await createRouter({
    logger: env.logger,
    config: env.config,
  });
}
```

Im using `""@vippsno/plugin-azure-resources-backend": "^1.0.6""`
on Backstage `"version": "1.24.2"`

After running `yarn dev`

```
yarn dev
yarn run v1.22.21
$ concurrently "yarn start" "yarn start-backend"
$ yarn workspace app start
$ yarn workspace backend start
$ backstage-cli package start
$ backstage-cli package start
[0] Loaded config from app-config.yaml, app-config.local.yaml
[0] <i> [webpack-dev-server] Project is running at:
[0] <i> [webpack-dev-server] Loopback: http://localhost:3000/, http://127.0.0.1:3000/
[0] <i> [webpack-dev-server] Content not from webpack is served from '/mypath/Backstage/packages/app/public' directory
[0] <i> [webpack-dev-server] 404s will fallback to '/index.html'
[1] node:internal/modules/cjs/loader:1137
[1]   throw err;
[1]   ^
[1]
[1] Error: Cannot find module '@vippsno/plugin-azure-resources-backend'
[1] Require stack:
[1] - /mypath/Backstage/packages/backend/src/plugins/azure-resources-backend.ts
[1] - /mypath/Backstage/packages/backend/src/index.ts
[1]     at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
[1]     at Module._load (node:internal/modules/cjs/loader:975:27)
[1]     at Module.require (node:internal/modules/cjs/loader:1225:19)
[1]     at require (node:internal/modules/helpers:177:18)
[1]     at Object.<anonymous> (/mypath/Backstage/packages/backend/src/plugins/azure-resources-backend.ts:5:31)
[1]     at Module._compile (node:internal/modules/cjs/loader:1356:14)
[1]     at Module._compile (/mypath/Backstage/node_modules/pirates/lib/index.js:117:24)
[1]     at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
[1]     at Object.newLoader [as .ts] (/mypath/Backstage/node_modules/pirates/lib/index.js:121:7)
[1]     at Module.load (node:internal/modules/cjs/loader:1197:32)
[1]     at Module._load (node:internal/modules/cjs/loader:1013:12)
[1]     at Module.require (node:internal/modules/cjs/loader:1225:19)
[1]     at require (node:internal/modules/helpers:177:18)
[1]     at Object.<anonymous> (/mypath/Backstage/packages/backend/src/index.ts:42:28)
[1]     at Module._compile (node:internal/modules/cjs/loader:1356:14)
[1]     at Module._compile (/mypath/Backstage/node_modules/pirates/lib/index.js:117:24) {
[1]   code: 'MODULE_NOT_FOUND',
[1]   requireStack: [
[1]     '/mypath/Backstage/packages/backend/src/plugins/azure-resources-backend.ts',
[1]     '/mypath/Backstage/packages/backend/src/index.ts'
[1]   ]
[1] }
[1]
[1] Node.js v18.19.1
[0] <i> [webpack-dev-middleware] wait until bundle finished: /
[0] webpack compiled successfully
^[[A^C
[0] <i> [webpack-dev-server] Gracefully shutting down. To force exit, press ^C again. Please wait...
```

What i've tried: deleting all `node_modules` folders and run `yarn install`, no success

**Comment by MaciekStrzelbicki** [comment]
Same here, version 1.0.6 wont build, there is no /dist folder in node_modules, when using 
"@vippsno/plugin-azure-resources-backend": "1.0.5",
without ^ and ~ it works
